### ISSUE TITLE
Filtering categories

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/HCS-Tools#14]
Filtering plates works nicely, but how are these search columns defined/selected?
Column names are different in the table, data = Date of Acquisition? (in our case that is rather the data of experiment/run)
Would it be useful/possible to make filtering on all selected factor columns?

**Comment by fmeyenhofer** [comment]
The filtering currently works on the plate attributes that were extracted from the barcode when executing the node (parsing the table into Plate objects).
From a technical point of view this is convenient, since each plate has only one possible value for each barcode attribute. However a plate can have a multitude of values for a given factor. It is possible of course to implement the plate filtering on factors, but it would slow the plate filtering process down a lot.
How about filtering plates before using the PlateHeatMapViewer node?

**Comment by stoeter** [comment]
Of cause that always could be done. 
Does that mean it uses the standard plate attributes of the barcode (plate number, project name, date, replicate, library code and assay) that is hidden somewhere in the code? Antje mentioned already that this should be replaced by configurable regex set in preferences. There only the above listed attributes can be used. Well i think this is then a longer story and has to be changed later....
Definitely "Date of acquisition" should then be renamed to 'Date", cause in the barcode is data of experiment.

**Comment by niederle** [comment]
might be outdated. reopen if necessary
